name: camera_windows
description: A Flutter plugin for getting information about and controlling the camera on Windows.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.2

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: camera
    platforms:
      windows:
        pluginClass: CameraWindows
        dartPluginClass: CameraWindows

dependencies:
  camera_platform_interface: 
    git:
      url: https://github.com/filipsky/packages
      ref: git_build
      path: packages/camera/camera_platform_interface
  cross_file: ^0.3.1
  flutter:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter

topics:
  - camera
